server:
  port: 8080
spring:
  application:
    name: agricultural-service
  datasource:
    url: "jdbc:mysql://localhost:3312/agricultural_database"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
adafruit:
  username: diavolo
  feed: lightkey
  aio-key: aio_AnXx61cSx9X0H2v76WrW92dOXFYY
