server:
  port: 8080
spring:
  application:
    name: agricultural-service
  datasource:
    #    url: "jdbc:mysql://localhost:3312/agricultural_database"
    #    driverClassName: "com.mysql.cj.jdbc.Driver"
    #    username: root
    #    password: 12345678
    url: jdbc:mysql://key:23641/agriculture?ssl-mode=REQUIRED
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: key
    password: key
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
adafruit:
  username: key
  feed: key
  aio-key: key_in_here
  water-pump: water-pump
  light: light
  fan: fan
